import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Dairy & Eggs (Category 1)
        {
            name: 'Amul Fresh Milk - 500ml',
            description: 'Fresh full cream milk from Amul, rich in calcium and protein. Perfect for daily consumption.',
            price: 28.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/amul-milk.jpg',
            categoryId: 1,
            stockQuantity: 85,
            deliveryTime: '8 mins',
            rating: 4.5,
            reviewCount: 156,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Amul Salted Butter - 100g',
            description: 'Premium quality salted butter made from fresh cream. Ideal for cooking and spreading.',
            price: 62.0,
            discountedPrice: 55.0,
            imageUrl: 'https://example.com/amul-butter.jpg',
            categoryId: 1,
            stockQuantity: 42,
            deliveryTime: '8 mins',
            rating: 4.7,
            reviewCount: 289,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Mother Dairy Curd - 400g',
            description: 'Fresh and creamy curd made from pure milk. Rich source of probiotics and calcium.',
            price: 32.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/mother-dairy-curd.jpg',
            categoryId: 1,
            stockQuantity: 67,
            deliveryTime: '8 mins',
            rating: 4.3,
            reviewCount: 98,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Amul Cheese Slices - 200g',
            description: 'Processed cheese slices perfect for sandwiches and burgers. Made with pure milk.',
            price: 125.0,
            discountedPrice: 110.0,
            imageUrl: 'https://example.com/amul-cheese.jpg',
            categoryId: 1,
            stockQuantity: 34,
            deliveryTime: '8 mins',
            rating: 4.4,
            reviewCount: 167,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Farm Fresh Eggs - 6 pieces',
            description: 'Fresh country eggs from free-range hens. High in protein and essential nutrients.',
            price: 45.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/fresh-eggs.jpg',
            categoryId: 1,
            stockQuantity: 78,
            deliveryTime: '10 mins',
            rating: 4.2,
            reviewCount: 134,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Amul Paneer - 200g',
            description: 'Fresh cottage cheese made from pure milk. Perfect for Indian curries and snacks.',
            price: 85.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/amul-paneer.jpg',
            categoryId: 1,
            stockQuantity: 29,
            deliveryTime: '8 mins',
            rating: 4.6,
            reviewCount: 203,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Fruits & Vegetables (Category 2)
        {
            name: 'Fresh Bananas - 1 dozen',
            description: 'Ripe yellow bananas rich in potassium and natural sugars. Perfect for healthy snacking.',
            price: 48.0,
            discountedPrice: 42.0,
            imageUrl: 'https://example.com/bananas.jpg',
            categoryId: 2,
            stockQuantity: 95,
            deliveryTime: '8 mins',
            rating: 4.1,
            reviewCount: 87,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Red Onions - 1kg',
            description: 'Fresh red onions sourced directly from farms. Essential ingredient for Indian cooking.',
            price: 35.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/red-onions.jpg',
            categoryId: 2,
            stockQuantity: 120,
            deliveryTime: '8 mins',
            rating: 4.0,
            reviewCount: 156,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Fresh Tomatoes - 1kg',
            description: 'Juicy red tomatoes perfect for cooking and salads. Rich in vitamins and antioxidants.',
            price: 42.0,
            discountedPrice: 38.0,
            imageUrl: 'https://example.com/tomatoes.jpg',
            categoryId: 2,
            stockQuantity: 87,
            deliveryTime: '8 mins',
            rating: 3.9,
            reviewCount: 124,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Fresh Potatoes - 2kg',
            description: 'High quality potatoes perfect for various Indian preparations. Freshly harvested.',
            price: 56.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/potatoes.jpg',
            categoryId: 2,
            stockQuantity: 142,
            deliveryTime: '10 mins',
            rating: 4.2,
            reviewCount: 89,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Green Capsicum - 500g',
            description: 'Fresh green bell peppers perfect for stir-fries and curries. Crisp and nutritious.',
            price: 65.0,
            discountedPrice: 58.0,
            imageUrl: 'https://example.com/green-capsicum.jpg',
            categoryId: 2,
            stockQuantity: 56,
            deliveryTime: '8 mins',
            rating: 4.3,
            reviewCount: 67,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Fresh Spinach - 250g',
            description: 'Fresh green spinach leaves rich in iron and vitamins. Perfect for healthy cooking.',
            price: 28.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/spinach.jpg',
            categoryId: 2,
            stockQuantity: 73,
            deliveryTime: '8 mins',
            rating: 4.1,
            reviewCount: 45,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Bakery & Snacks (Category 3)
        {
            name: 'Britannia Bread - White 400g',
            description: 'Soft and fresh white bread from Britannia. Perfect for sandwiches and toast.',
            price: 28.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/britannia-bread.jpg',
            categoryId: 3,
            stockQuantity: 65,
            deliveryTime: '8 mins',
            rating: 4.4,
            reviewCount: 178,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Parle-G Biscuits - 200g',
            description: 'Classic glucose biscuits from Parle. Perfect tea-time companion loved by all ages.',
            price: 25.0,
            discountedPrice: 22.0,
            imageUrl: 'https://example.com/parle-g.jpg',
            categoryId: 3,
            stockQuantity: 145,
            deliveryTime: '8 mins',
            rating: 4.6,
            reviewCount: 267,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Britannia Good Day Cookies - 150g',
            description: 'Delicious butter cookies with cashew and almond. Premium quality from Britannia.',
            price: 45.0,
            discountedPrice: 40.0,
            imageUrl: 'https://example.com/good-day.jpg',
            categoryId: 3,
            stockQuantity: 89,
            deliveryTime: '8 mins',
            rating: 4.5,
            reviewCount: 234,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Haldiram\'s Bhujia - 200g',
            description: 'Crispy and spicy namkeen made from gram flour. A popular snack from Haldiram\'s.',
            price: 85.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/haldirams-bhujia.jpg',
            categoryId: 3,
            stockQuantity: 67,
            deliveryTime: '8 mins',
            rating: 4.7,
            reviewCount: 189,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Britannia Marie Gold - 250g',
            description: 'Light and crispy marie biscuits. Perfect for tea and coffee pairing.',
            price: 35.0,
            discountedPrice: 32.0,
            imageUrl: 'https://example.com/marie-gold.jpg',
            categoryId: 3,
            stockQuantity: 123,
            deliveryTime: '8 mins',
            rating: 4.3,
            reviewCount: 156,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Haldiram\'s Moong Dal - 150g',
            description: 'Crunchy roasted moong dal seasoned with spices. Healthy and tasty snack option.',
            price: 65.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/moong-dal.jpg',
            categoryId: 3,
            stockQuantity: 78,
            deliveryTime: '10 mins',
            rating: 4.4,
            reviewCount: 98,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Beverages (Category 4)
        {
            name: 'Tata Tea Premium - 250g',
            description: 'Premium blend black tea with rich aroma and taste. Perfect for morning and evening tea.',
            price: 125.0,
            discountedPrice: 110.0,
            imageUrl: 'https://example.com/tata-tea.jpg',
            categoryId: 4,
            stockQuantity: 95,
            deliveryTime: '8 mins',
            rating: 4.5,
            reviewCount: 245,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Nescafe Classic Coffee - 100g',
            description: 'Instant coffee with rich and aromatic flavor. Made from premium coffee beans.',
            price: 285.0,
            discountedPrice: 255.0,
            imageUrl: 'https://example.com/nescafe.jpg',
            categoryId: 4,
            stockQuantity: 56,
            deliveryTime: '8 mins',
            rating: 4.6,
            reviewCount: 178,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Coca Cola - 750ml',
            description: 'Refreshing cola drink perfect for any occasion. Chilled and carbonated.',
            price: 45.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/coca-cola.jpg',
            categoryId: 4,
            stockQuantity: 134,
            deliveryTime: '8 mins',
            rating: 4.2,
            reviewCount: 267,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Real Mixed Fruit Juice - 1L',
            description: 'Delicious mixed fruit juice with real fruit pulp. Rich in vitamins and minerals.',
            price: 85.0,
            discountedPrice: 78.0,
            imageUrl: 'https://example.com/real-juice.jpg',
            categoryId: 4,
            stockQuantity: 67,
            deliveryTime: '10 mins',
            rating: 4.1,
            reviewCount: 123,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Bisleri Water - 1L',
            description: 'Pure and safe drinking water. Mineral water processed with advanced purification.',
            price: 20.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/bisleri.jpg',
            categoryId: 4,
            stockQuantity: 189,
            deliveryTime: '8 mins',
            rating: 4.0,
            reviewCount: 89,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Lipton Green Tea - 100g',
            description: 'Premium green tea bags with natural antioxidants. Healthy and refreshing.',
            price: 165.0,
            discountedPrice: 145.0,
            imageUrl: 'https://example.com/lipton-green-tea.jpg',
            categoryId: 4,
            stockQuantity: 45,
            deliveryTime: '8 mins',
            rating: 4.3,
            reviewCount: 156,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Personal Care (Category 5)
        {
            name: 'Colgate Total Toothpaste - 150g',
            description: 'Advanced toothpaste with 12-hour protection against germs. Fresh mint flavor.',
            price: 145.0,
            discountedPrice: 125.0,
            imageUrl: 'https://example.com/colgate.jpg',
            categoryId: 5,
            stockQuantity: 78,
            deliveryTime: '8 mins',
            rating: 4.4,
            reviewCount: 203,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Patanjali Aloe Vera Gel - 150ml',
            description: 'Pure aloe vera gel for skin care. Natural and chemical-free skincare solution.',
            price: 85.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/patanjali-aloe.jpg',
            categoryId: 5,
            stockQuantity: 92,
            deliveryTime: '8 mins',
            rating: 4.2,
            reviewCount: 167,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Head & Shoulders Shampoo - 340ml',
            description: 'Anti-dandruff shampoo with zinc pyrithione. Clinically proven dandruff protection.',
            price: 285.0,
            discountedPrice: 255.0,
            imageUrl: 'https://example.com/head-shoulders.jpg',
            categoryId: 5,
            stockQuantity: 56,
            deliveryTime: '10 mins',
            rating: 4.5,
            reviewCount: 189,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Dettol Hand Wash - 250ml',
            description: 'Antibacterial liquid hand wash with original Dettol formula. Kills 99.9% germs.',
            price: 85.0,
            discountedPrice: 75.0,
            imageUrl: 'https://example.com/dettol-handwash.jpg',
            categoryId: 5,
            stockQuantity: 134,
            deliveryTime: '8 mins',
            rating: 4.6,
            reviewCount: 234,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Nivea Soft Moisturizer - 100ml',
            description: 'Light moisturizing cream with jojoba oil and vitamin E. Suitable for all skin types.',
            price: 165.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/nivea-soft.jpg',
            categoryId: 5,
            stockQuantity: 67,
            deliveryTime: '8 mins',
            rating: 4.3,
            reviewCount: 145,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Gillette Mach3 Razor',
            description: 'Premium 3-blade razor with comfort guard. Smooth and comfortable shaving experience.',
            price: 425.0,
            discountedPrice: 375.0,
            imageUrl: 'https://example.com/gillette-mach3.jpg',
            categoryId: 5,
            stockQuantity: 34,
            deliveryTime: '10 mins',
            rating: 4.7,
            reviewCount: 189,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Household Items (Category 6)
        {
            name: 'Vim Dishwash Liquid - 500ml',
            description: 'Powerful grease cutting formula for effective dishwashing. Lemon fresh fragrance.',
            price: 95.0,
            discountedPrice: 85.0,
            imageUrl: 'https://example.com/vim-liquid.jpg',
            categoryId: 6,
            stockQuantity: 89,
            deliveryTime: '8 mins',
            rating: 4.3,
            reviewCount: 156,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Surf Excel Detergent - 1kg',
            description: 'Advanced stain removal detergent powder. Removes tough stains easily.',
            price: 185.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/surf-excel.jpg',
            categoryId: 6,
            stockQuantity: 123,
            deliveryTime: '10 mins',
            rating: 4.5,
            reviewCount: 267,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Harpic Toilet Cleaner - 500ml',
            description: 'Powerful toilet bowl cleaner that kills 99.9% germs. Fresh citrus fragrance.',
            price: 125.0,
            discountedPrice: 110.0,
            imageUrl: 'https://example.com/harpic.jpg',
            categoryId: 6,
            stockQuantity: 67,
            deliveryTime: '8 mins',
            rating: 4.4,
            reviewCount: 134,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Colin Glass Cleaner - 250ml',
            description: 'Streak-free glass and surface cleaner. Leaves surfaces sparkling clean.',
            price: 85.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/colin.jpg',
            categoryId: 6,
            stockQuantity: 78,
            deliveryTime: '8 mins',
            rating: 4.2,
            reviewCount: 98,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Lizol Disinfectant - 500ml',
            description: 'Floor cleaner and disinfectant that kills germs. Citrus fresh fragrance.',
            price: 145.0,
            discountedPrice: 130.0,
            imageUrl: 'https://example.com/lizol.jpg',
            categoryId: 6,
            stockQuantity: 92,
            deliveryTime: '10 mins',
            rating: 4.6,
            reviewCount: 178,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Good Knight Mosquito Coil - 10 pieces',
            description: 'Effective mosquito repellent coils. Provides 8-hour protection from mosquitoes.',
            price: 45.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/good-knight.jpg',
            categoryId: 6,
            stockQuantity: 145,
            deliveryTime: '8 mins',
            rating: 4.1,
            reviewCount: 89,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Ready to Eat (Category 7)
        {
            name: 'Maggi 2-Minute Noodles - 420g',
            description: 'Classic masala instant noodles. Ready in just 2 minutes with delicious taste.',
            price: 85.0,
            discountedPrice: 78.0,
            imageUrl: 'https://example.com/maggi-noodles.jpg',
            categoryId: 7,
            stockQuantity: 156,
            deliveryTime: '8 mins',
            rating: 4.6,
            reviewCount: 345,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'MTR Ready to Eat Pulao - 300g',
            description: 'Authentic vegetable pulao ready in 3 minutes. Traditional Indian flavors.',
            price: 125.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/mtr-pulao.jpg',
            categoryId: 7,
            stockQuantity: 67,
            deliveryTime: '10 mins',
            rating: 4.4,
            reviewCount: 167,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'ITC Ready to Eat Dal Makhani - 300g',
            description: 'Rich and creamy dal makhani ready in minutes. Restaurant-style taste at home.',
            price: 145.0,
            discountedPrice: 130.0,
            imageUrl: 'https://example.com/itc-dal-makhani.jpg',
            categoryId: 7,
            stockQuantity: 45,
            deliveryTime: '8 mins',
            rating: 4.5,
            reviewCount: 234,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Haldiram\'s Chole Bhature - 300g',
            description: 'Traditional North Indian dish ready to eat. Authentic taste and spices.',
            price: 165.0,
            discountedPrice: 148.0,
            imageUrl: 'https://example.com/haldirams-chole.jpg',
            categoryId: 7,
            stockQuantity: 56,
            deliveryTime: '8 mins',
            rating: 4.3,
            reviewCount: 189,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Knorr Soup Mix - 4 Serves',
            description: 'Instant soup mix in tomato flavor. Hot and comforting soup ready in minutes.',
            price: 65.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/knorr-soup.jpg',
            categoryId: 7,
            stockQuantity: 89,
            deliveryTime: '8 mins',
            rating: 4.2,
            reviewCount: 123,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Saffola Oats - 400g',
            description: 'Healthy and nutritious oats perfect for breakfast. High in fiber and protein.',
            price: 185.0,
            discountedPrice: 165.0,
            imageUrl: 'https://example.com/saffola-oats.jpg',
            categoryId: 7,
            stockQuantity: 78,
            deliveryTime: '10 mins',
            rating: 4.4,
            reviewCount: 156,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Cooking Essentials (Category 8)
        {
            name: 'Fortune Sunflower Oil - 1L',
            description: 'Refined sunflower oil with Vitamin A, D & E. Perfect for all types of cooking.',
            price: 165.0,
            discountedPrice: 148.0,
            imageUrl: 'https://example.com/fortune-oil.jpg',
            categoryId: 8,
            stockQuantity: 134,
            deliveryTime: '8 mins',
            rating: 4.5,
            reviewCount: 289,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Tata Salt - 1kg',
            description: 'Iodized salt enriched with iron. Essential for healthy cooking and nutrition.',
            price: 28.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/tata-salt.jpg',
            categoryId: 8,
            stockQuantity: 167,
            deliveryTime: '8 mins',
            rating: 4.3,
            reviewCount: 234,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'India Gate Basmati Rice - 1kg',
            description: 'Premium long grain basmati rice with authentic aroma and taste.',
            price: 185.0,
            discountedPrice: 165.0,
            imageUrl: 'https://example.com/india-gate-rice.jpg',
            categoryId: 8,
            stockQuantity: 89,
            deliveryTime: '10 mins',
            rating: 4.6,
            reviewCount: 345,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'MDH Garam Masala - 100g',
            description: 'Authentic blend of aromatic spices for Indian cooking. Premium quality spices.',
            price: 65.0,
            discountedPrice: 58.0,
            imageUrl: 'https://example.com/mdh-garam-masala.jpg',
            categoryId: 8,
            stockQuantity: 123,
            deliveryTime: '8 mins',
            rating: 4.7,
            reviewCount: 178,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Everest Turmeric Powder - 200g',
            description: 'Pure turmeric powder with natural color and aroma. Essential Indian spice.',
            price: 85.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/everest-turmeric.jpg',
            categoryId: 8,
            stockQuantity: 98,
            deliveryTime: '8 mins',
            rating: 4.4,
            reviewCount: 156,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Toor Dal - 1kg',
            description: 'High quality arhar dal, rich in protein. Essential ingredient for Indian meals.',
            price: 145.0,
            discountedPrice: 135.0,
            imageUrl: 'https://example.com/toor-dal.jpg',
            categoryId: 8,
            stockQuantity: 76,
            deliveryTime: '10 mins',
            rating: 4.2,
            reviewCount: 134,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Health & Wellness (Category 9)
        {
            name: 'Dabur Chyawanprash - 450g',
            description: 'Ayurvedic immunity booster with 40+ herbs. Builds immunity and strength naturally.',
            price: 285.0,
            discountedPrice: 255.0,
            imageUrl: 'https://example.com/dabur-chyawanprash.jpg',
            categoryId: 9,
            stockQuantity: 67,
            deliveryTime: '8 mins',
            rating: 4.5,
            reviewCount: 234,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Patanjali Giloy Juice - 500ml',
            description: 'Natural immunity booster made from pure giloy. Helps build natural resistance.',
            price: 125.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/patanjali-giloy.jpg',
            categoryId: 9,
            stockQuantity: 89,
            deliveryTime: '10 mins',
            rating: 4.3,
            reviewCount: 167,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Himalaya Liv.52 Tablets - 100 tabs',
            description: 'Liver health support tablets with natural herbs. Clinically proven formula.',
            price: 165.0,
            discountedPrice: 148.0,
            imageUrl: 'https://example.com/himalaya-liv52.jpg',
            categoryId: 9,
            stockQuantity: 45,
            deliveryTime: '8 mins',
            rating: 4.4,
            reviewCount: 189,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Baidyanath Ashwagandha Churna - 100g',
            description: 'Pure ashwagandha powder for stress relief and energy. Ayurvedic wellness supplement.',
            price: 185.0,
            discountedPrice: 165.0,
            imageUrl: 'https://example.com/baidyanath-ashwagandha.jpg',
            categoryId: 9,
            stockQuantity: 56,
            deliveryTime: '10 mins',
            rating: 4.6,
            reviewCount: 145,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Zandu Pancharishta - 450ml',
            description: 'Ayurvedic digestive tonic with 15 herbs. Improves digestion and appetite.',
            price: 145.0,
            discountedPrice: 130.0,
            imageUrl: 'https://example.com/zandu-pancharishta.jpg',
            categoryId: 9,
            stockQuantity: 78,
            deliveryTime: '8 mins',
            rating: 4.2,
            reviewCount: 123,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Patanjali Honey - 500g',
            description: 'Pure and natural honey tested for purity. Rich in minerals and antioxidants.',
            price: 225.0,
            discountedPrice: null,
            imageUrl: 'https://example.com/patanjali-honey.jpg',
            categoryId: 9,
            stockQuantity: 34,
            deliveryTime: '8 mins',
            rating: 4.7,
            reviewCount: 267,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        }
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});